<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <OutputPath>..\Bin\UnitTest</OutputPath>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DH.NCode" Version="4.25.2026.906-beta0436" />
    <PackageReference Include="DH.NCore" Version="4.25.2026.906-beta0249" />
    <PackageReference Include="DH.NIP" Version="4.25.2026.906-beta0756" />
    <PackageReference Include="DH.UnitTest" Version="4.25.2026.827-beta0613" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DH.NNovaDb\DH.NNovaDb.csproj" />
  </ItemGroup>

</Project>
